LoadMap = function(scene, af)

	-- tileData table should (probably?) be cleared and re-initialized
	-- each time we load a map.  Otherwise, it would potentially be larger than necessary.
	TSH.TileData = {
		TileSize = nil,
		CollisionTiles = {},
		EventTiles = {},
		Width = { Pixels = nil, Tiles = nil },
		Height = { Pixels = nil, Tiles = nil}
	}

	-- grab the entire tile-data file for the active scene
	-- these files were autogenerated by Tiled (http://www.mapeditor.org/)
	local tiledata = LoadActor("Scenes/" .. scene .. "/tile-data.lua")

	-- NOTE: the entire system is currently hardcoded to only work with
	-- 		square tiles; it assumes that tile width == tile height

	-- store map tile width and height
	TSH.TileData.Width.Tiles = tiledata.width
	TSH.TileData.Height.Tiles= tiledata.height

	-- get the width of a tile; all values below depend on it
	TSH.TileData.TileSize = tiledata.tilewidth
	-- store map pixel width and height
	TSH.TileData.Width.Pixels	= tiledata.width * tiledata.tilewidth
	TSH.TileData.Height.Pixels	= tiledata.height * tiledata.tilewidth
	-- store screen tile width and height
	TSH.Screen.Height.Tiles = TSH.Screen.Height.Pixels/tiledata.tilewidth
	TSH.Screen.Width.Tiles	= TSH.Screen.Width.Pixels/tiledata.tilewidth

	-- initialize the CollisionTiles table to be the necessary size, and filled with 0s
	-- for i=1 loops are supposedly faster than ipairs() so use where possible/sensible
	for i=1, (TSH.TileData.Width.Tiles * TSH.TileData.Height.Tiles) do
		TSH.TileData.CollisionTiles[i] = 0
	end

	-- we're only interested in the layer data for the sake of handling collisions
	-- so, loop through each layer that was exported
	for key,layer in ipairs(tiledata.layers) do

		-- but only bother with layers that have been named "Collision" by Caitlin
		if layer.name == "Collision" then

			-- there could be multiple such layers, which we want to collapse into one for
			-- the sake of speedy collision checking later
			for i=1, #layer.data do

				-- the tile ID doesn't matter; if it isn't 0, we collide with it
				if layer.data[i] ~= 0 then

					-- save 1s where collisions will occur
					TSH.TileData.CollisionTiles[i] = 1
				end
			end

		-- There will (should) be only be a single "Event" layer per map.
		elseif layer.name == "Event" then
			TSH.TileData.EventTiles = layer.data
		end
	end

	-- get event data for this map
	TSH.EventData = LoadActor("Scenes/" .. scene .. "/event-data.lua")
	-- local BGM = TSH.EventData.BGM
	local Start = TSH.EventData.Start

	-- initialize starting locations
	TSH.P1.pos.d, TSH.P1.pos.r = Start.P1.d, Start.P1.r
	TSH.P2.pos.d, TSH.P2.pos.r = Start.P2.d, Start.P2.r

	-- -- now that TileData has been processed, actually load visuals
	-- af:GetChild("Visuals"):playcommand("Load",{scene=scene})
	-- -- and audio
	-- af:GetChild("BGM"):playcommand("Set", {BGM=BGM}):queuecommand("Play")
end


Distance = function(direction)
	if direction == "d" then
		return math.abs(TSH.P1.pos.d - TSH.P2.pos.d)
	elseif direction == "r" then
		return math.abs(TSH.P1.pos.r - TSH.P2.pos.r)
	end
	return false
end


-- returns a table of two values, right and down, both in tile units
FindCenterOfMap = function()
	-- calculate which tile currently represents map center in terms of tiles right and tiles down from top-left (1,1)
	local r, d = (TSH.P1.pos.r + TSH.P2.pos.r)/2, (TSH.P1.pos.d + TSH.P2.pos.d)/2
	local MapCenter = {right = r, down = d}

	-- half screen width in tile units
	local half_screen_width_in_tiles  = TSH.Screen.Width.Tiles/2
	-- half screen height in tile units
	local half_screen_height_in_tiles = TSH.Screen.Height.Tiles/2

	-- if players are near the edge of a map, using the MapCenter as calculated above
	-- will result in the map scrolling "too far" and the player seeing beyond the edge of the map
	-- clamp the MapCenter values here to prevent this from occuring

	-- left edge of map
	if (MapCenter.right < half_screen_width_in_tiles) then MapCenter.right = half_screen_width_in_tiles end
	-- right edge of map
	if (MapCenter.right > TSH.TileData.Width.Tiles - half_screen_width_in_tiles) then MapCenter.right = TSH.TileData.Width.Tiles - half_screen_width_in_tiles end
	-- top edge of map
	if (MapCenter.down < half_screen_height_in_tiles) then MapCenter.down = half_screen_height_in_tiles end
	-- bottom edge of map
	if (MapCenter.down > TSH.TileData.Height.Tiles - half_screen_height_in_tiles) then MapCenter.down = TSH.TileData.Height.Tiles - half_screen_height_in_tiles end

	return MapCenter
end

OtherPlayer = function(pn)
	if pn == "P1" then
		return "P2"
	elseif pn == "P2" then
		return "P1"
	end
end